name: 'Copy Files to Repo'
description: 'Copy and  push files to repository'
inputs:
  source-directory:
    required: true
  username:
    required: true
  target-repo-name:
    required: true
  target-branch:
    default: 'main'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-directory }}
    - ${{ inputs.username }}
    - ${{ inputs.target-repo-name }}
    - ${{ inputs.user-email }}
    - ${{ inputs.target-branch }}